writeReport was throwing away the cause (Throwable) for failed commands. Now it sends back Throwable.toString as an attribute nam,ed "cause"
CLI Output:

----------------- BEFORE --------------------
FAILURE : GlassFish 10.0-SNAPSHOT (build b001)
---------------------------------------------

----------------- AFTER --------------------
FAILURE : GlassFish 10.0-SNAPSHOT (build b001)
java.lang.RuntimeException: test error here!!!
---------------------------------------------




git-svn-id: svn+ssh://svn.java.net/glassfish~svn/trunk@19484 6f3ba3e3-413c-0410-a8aa-90bee3ab43b5