We need to catch Throwable, otherwise we can server not to shutdown when the following happens: Assume a bundle which has registered a event listener has been uninstalled without unregistering the listener. listener.getClass() refers to a class of such an uninstalled bundle. If framework has been refreshed, then the classloader can't be used further to load any classes. As a result, an exception like NoClassDefFoundError is thrown when a stale listener is used. That's why event listener model is a bad model in a dynamic environment like OSGi. Whiteboard pattern is recommended.
git-svn-id: svn+ssh://svn.java.net/glassfish~svn/trunk@29538 6f3ba3e3-413c-0410-a8aa-90bee3ab43b5