Issue 11589. More lenient with NoClassDefFoundError during annotation processing, log a warning and continue instead of aborting the processing. Ran QL, deployment dev tests.
git-svn-id: svn+ssh://svn.java.net/glassfish~svn/trunk@35714 6f3ba3e3-413c-0410-a8aa-90bee3ab43b5